---
functional:
  - Пользователь должен иметь возможность регистрации на сайте
  - Пользователь должен иметь возможность выбора языка программирования
  - Пользователь должен иметь возможность видеть код соперника в реальном времени
  - Пользователь должен иметь возможность написания сообщений в чате
  - Пользователь должен иметь возможность самостоятельного создания игры
  - Пользователь должен иметь возможность вступления в открытые игры
  - Пользователь должен иметь возможность выбора соревнований с ботом, или реальным человеком
  - Пользователь должен иметь возможность наблюдения за рейтингом
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен предоставлять возможность регистрации новых пользователей
  - Сайт должен предоставлять возможность входа в личный кабинет для зарегистрированных пользователей
  - Сайт должен предоставлять возможность выхода из личного кабинета
  - Сайт должен иметь кнопку запуска игры
  - Сайт должен иметь кнопку создания игры
  - Сайт должен предоставлять возможность изменения языка программирования в игре
  - Все кнопки на странице должны быть кликабельны
  - Все кнопки на странице должны функционировать по назначению
    



